modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${issues_url}"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="${mod_logo}"
credits="${credits}"
authors="${author}"
description='''Blocks Input Methods when you're not using it.
在你不打字的时候自动关闭输入法'''
[[mixins]]
config = "META-INF/imblocker.mixins.json"
